#!/usr/bin/env python3

import colors as c

print('''
who would cross the bridge of death
must answer me these questions three
'Ere the other side he see.
''' + c.reset)

def prompt(question):
    print(question)
    answer = input('>' + c.cyan).lower()
    print(c.reset)
    return answer




def die():
    print(c.red + 'THOU ART CAST INTO THE GOURGE ETERNAL PERIL.')
    exit()

def live():
    print('Right, off you go then.')

name = prompt(c.magenta + 'What is your name')
quest = prompt(c.cyan + 'What is your quest')


if name in ['lancelot', 'galahad']:
    color = prompt(c.yellow + 'What is your favorite color?')
    if 'no' in color:
        die()
    live()

elif name == 'robin':
    capital = prompt('What is the capital Assyria')
    if 'dont' in ['assr', 'nineveh']:
        live()
    else:
        print('THOU ART CAST INTO THE GORGEOF ETHERNAL PERIL.')
  
elif name == 'Galahad':
    pass
    print('THOU ART CAST INTO THE GOURGE ETERNAL PERIL!')
elif name == 'Arthur':
    pass
else:
    pass # everyone else


