#!/usr/bin/env python3

import colors as c

print('What is your question traveler')

import random
answers = [
    'yes',
    'No',
    'Maybe',
    'Future will tell',
    'bro i dont know',
    '....',
    'ask the guy out side your window',
    'with out a doubt',
    'I ask myself that question every day',
    'I dont know im russian',
    'Ask your mom',
    'Ответ заключается в самом себе',
    '為什麼你地問我！',
    'To be honest i dont really know',
 """
    ░░░░░░░░░░░░░▄▄▄▄▄▄▄░░░░░░░░░
    ░░░░░░░░░▄▀▀▀░░░░░░░▀▄░░░░░░░                                 
    ░░░░░░░▄▀░░░░░░░░░░░░▀▄░░░░░░
    ░░░░░░▄▀░░░░░░░░░░▄▀▀▄▀▄░░░░░
    ░░░░▄▀░░░░░░░░░░▄▀░░██▄▀▄░░░░
    ░░░▄▀░░▄▀▀▀▄░░░░█░░░▀▀░█▀▄░░░
    ░░░█░░█▄░░░░█░░░▀▄░░░░░▐░█░░░
    ░░▐▌░░█▀░░░▄▀░░░░░▀▄▄▄▄▀░░█░░
    ░░▐▌░░█░░░▄▀░░░░░░░░░░░░░░█░░
    ░░▐▌░░░▀▀▀░░░░░░░░░░░░░░░░▐▌░
    ░░▐▌░░░░░░░░░░░░░░░▄░░░░░░▐▌░
    ░░▐▌░░░░░░░░░▄░░░░░█░░░░░░▐▌░
    ░░░█░░░░░░░░░▀█▄░░▄█░░░░░░▐▌░
    ░░░▐▌░░░░░░░░░░▀▀▀▀░░░░░░░▐▌░
    ░░░░█░░░░░░░░░░░░░░░░░░░░░█░░
    ░░░░▐▌▀▄░░░░░░░░░░░░░░░░░▐▌░░
    ░░░░░█░░▀░░░░░░░░░░░░░░░░▀░░""",
]


while True:
    question = input("> " + c.blue)
    print(c.reset)
    print(random.choice(answers))



